org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=256m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false
android.builder.sdkDownload=false
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
android.enableJetifier=false
